name: Release GoBackup binaries

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows]
        goarch: [amd64]
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      uses: nida/go-release-action@v3.2.6
      env: 
        CGO_ENABLED: 1 
        CC: x86_64-w64-mingw32-gcc
        CXX: x86_64-w64-mingw32-g++
        HOST: x86_64-w64-mingw32
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: https://golang.org/dl/go1.18.1.linux-amd64.tar.gz
        pre_command: apt-get update -y && apt-get install -y mingw-w64
        ldflags: "-s -w -H windowsgui -extldflags -static"
        binary_name: "GoBackup"